[build]
  command = "vite build storybook-static"
  publish = "storybook-static"

[build.environment]
  NODE_VERSION = "14"
  YARN_VERSION = "1.22.10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200