#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BASE=main
HEAD=HEAD

npx nx workspace-lint
npx nx affected --head=$HEAD --base=$BASE --target=prettier
npx nx affected --head=$HEAD --base=$BASE --target=lint
